name: CI

on:
  workflow_dispatch:
  push:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: editorconfig-checker/action-editorconfig-checker@v2
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
    - run: dotnet format Project.slnx --verify-no-changes
    - run: editorconfig-checker

  unit-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
    - run: dotnet test --logger "console;verbosity=detailed"

  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
    - run: dotnet publish src -c Release
    - uses: actions/upload-artifact@v4
      with:
        path: src/bin/Release/net9-windows/win-x64/native/*
        retention-days: 1
